[env:cardputer-adv]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB

lib_deps =
    m5stack/M5Cardputer
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/wakwak-koba/ESP32-NimBLE-Keyboard.git

build_flags =
    -DCORE_DEBUG_LEVEL=0

extra_scripts = post:scripts/merge_bin.py
